apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-server
  name: api-server
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
        - image: jwfeb05/jw-home-api-server:latest
          imagePullPolicy: Always
          name: api-server
          ports:
            - containerPort: 9092
          env:
            - name: MONGODB_HOST
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_HOST
            - name: MONGODB_PORT
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_PORT
            - name: MONGODB_USER
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_USER
            - name: MONGODB_PASS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: MONGODB_PASS
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_PORT
            - name: REDIS_PASS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: REDIS_PASS
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: KAFKA_BROKERS
            - name: JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: JWT_ISSUER_URI
            - name: JWT_SET_URI
              valueFrom:
                configMapKeyRef:
                  name: jw-home-cm
                  key: JWT_SET_URI
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: api-server
  name: api-server
  namespace: default
spec:
  ports:
    - port: 9092 #CHANGE
      protocol: TCP
      targetPort: 9092 #CHANGE
  selector:
    app: api-server
  sessionAffinity: None #CHANGE
  type: NodePort