server:
  port: 9092
spring:
  application:
    name: api-server
  data:
    mongodb:
      uri: mongodb://${MONGODB_USER:admin}:${MONGODB_PASS:pass}@${MONGODB_HOST:localhost}:${MONGODB_PORT:27017}/jw-home?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      authentication-database: admin
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASS:pass}
    pubsub:
      device:
        control-request-channel-postfix: -control-request
        control-response-channel-postfix: -control-response
        control-block-seconds: 15
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    consumer:
      group-id: group.device-state.save
    topics:
      device-state: ec2.jwhome.dev.device-state.json
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:http://localhost:8080/realms/jw-home}
          jwk-set-uri: ${JWT_SET_URI:http://localhost:8080/realms/jw-home/protocol/openid-connect/certs}
        opaquetoken:
          introspection-uri: http://url:9093/oauth/check_token
          client-id: jw-api-server
          client-secret: secret
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
eureka:
  instance:
    prefer-ip-address: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://127.0.0.1:8761/eureka}