server:
  port: 9092
spring:
  data:
    mongodb:
      uri: mongodb://user:pass@url:27017/jw-home?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false
      authentication-database: admin
  redis:
    host: host
    port: 6379
    password: password
    pubsub:
      device:
        control-request-channel-postfix: -control-request
        control-response-channel-postfix: -control-response
        control-block-seconds: 15
  kafka:
    bootstrap-servers: broker:9092
    consumer:
      group-id: group.device-state.save
    topics:
      device-state: ec2.jwhome.dev.device-state.json
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://url:9093/oauth/check_token
          client-id: jw-api-server
          client-secret: secret